version: '2'
services:
    db:
        image: postgres:13
        volumes:
            - ./db:/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=user
            - POSTGRES_DB=mydatabase
            - POSTGRES_PASSWORD=12345
            - PGDATA=/var/lib/postgresql/data/pgdata
    app:
        container_name: backend
        build:
            context: ./backend/
            dockerfile: Dockerfile
        ports:
            - "8080:8080"